version: "3.7"

services:
  postgres:
    image: postgres:12-alpine
    container_name: postgres12
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
